In [4]:
import torch

a = torch.rand(size=(1, 3, 3, 1))
print(a.shape)
a = a.squeeze(-1)
print(a.shape)

torch.Size([1, 3, 3, 1])
torch.Size([1, 3, 3])


In [4]:
from sklearn.model_selection import KFold
import numpy as np

a = np.arange(15)
kf = KFold(n_splits=5, shuffle=True, random_state=2021)
b = list(kf.split(a))
b

[(array([ 0,  1,  2,  4,  5,  6,  8,  9, 10, 12, 13, 14]),
  array([ 3,  7, 11])),
 (array([ 0,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14]),
  array([ 1,  2, 12])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 11, 12, 13]),
  array([ 8, 10, 14])),
 (array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 14]),
  array([ 0,  6, 13])),
 (array([ 0,  1,  2,  3,  6,  7,  8, 10, 11, 12, 13, 14]), array([4, 5, 9]))]

In [5]:
a = np.arange(15)
kf = KFold(n_splits=5, shuffle=True, random_state=2021)
b = list(kf.split(a))
b

[(array([ 0,  1,  2,  4,  5,  6,  8,  9, 10, 12, 13, 14]),
  array([ 3,  7, 11])),
 (array([ 0,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14]),
  array([ 1,  2, 12])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 11, 12, 13]),
  array([ 8, 10, 14])),
 (array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 14]),
  array([ 0,  6, 13])),
 (array([ 0,  1,  2,  3,  6,  7,  8, 10, 11, 12, 13, 14]), array([4, 5, 9]))]